make add anchor=super-nintendo name="Super Mario World™" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Super Mario World™ 2: Yoshi's Island" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Super Mario Kart™" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="The Legend of Zelda™: A Link to the Past" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Super Metroid™" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Star Fox™" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="F-ZERO™" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Stunt Race FX™" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Pilotwings™" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Kirby's Dream Land™ 3" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Kirby's Dream Course™" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Super Ghouls'n Ghosts™" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Demon's Crest" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Super Soccer" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Super Puyo Puyo 2" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Breath Of Fire" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="BRAWL BROTHERS" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="SUPER E.D.F. EARTH DEFENSE FORCE" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Super Tennis" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Joe & Mac 2: Lost in the Tropics" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Star Fox™ 2" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Super Punch-Out!!™" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Kirby Super Star™" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Breath of Fire II" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Pop'n TwinBee" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Smash Tennis™" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Operation Logic Bomb" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Wild Guns" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Panel de Pon" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Donkey Kong Country" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Natsume Championship Wrestling" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Donkey Kong Country 2: Diddy’s Kong-Quest" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Mario’s Super Picross" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="The Peace Keepers" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Donkey Kong Country 3: Dixie Kong’s Double Trouble!" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="The Ignition Factor" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Super Valis IV" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Tuff E Nuff" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Psycho Dream" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="DOOMSDAY WARRIOR" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Prehistorik Man" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Super Baseball Simulator 1,000" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Caveman Ninja also known as Joe Mac" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Magical Drop2" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Spanky’s™Quest" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Jelly Boy" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Bombuzal" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Claymates" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Super Mario All-Stars" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="The Peacekeepers" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="EarthBound™" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'
make add anchor=super-nintendo name="Earthworm Jim™ 2" website='https://www.nintendo.com/switch/online-service/super-nintendo-entertainment-system-nintendo-switch-online-switch/'

