name: Deno
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deno
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - run: deno --version
      - run: |
          make
          make summary
